services:
  db:
    image: postgres:17
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: graphein
      POSTGRES_PASSWORD: graphein
      POSTGRES_DB: graphein
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres:17
    ports:
      - "15433:5432"
    environment:
      POSTGRES_USER: graphein_test
      POSTGRES_PASSWORD: graphein_test
      POSTGRES_DB: graphein_test

volumes:
  pgdata:
