services:
  db:
    image: postgres:17
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: graphein
      POSTGRES_PASSWORD: graphein
      POSTGRES_DB: graphein
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
