name: Workflow Check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  actionlint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      # Hack to avoid error like https://github.com/nownabe/nabeoyaji.fish/actions/runs/21378412063/job/61611796368#step:3:134
      # See https://github.com/raven-actions/actionlint/blob/580b34edf3f0039a5691481c6081049971ecd530/action.yml#L207
      - name: Delete package.json
        run: rm -f package.json

      - name: Run actionlint
        uses: raven-actions/actionlint@e01d1ea33dd6a5ed517d95b4c0c357560ac6f518 # v2.1.1

  zizmor:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@135698455da5c3b3e55f73f4419e481ab68cdd95 # v0.4.1
        with:
          advanced-security: false

  ghalint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: stable

      - name: Install ghalint
        run: go install github.com/suzuki-shunsuke/ghalint/cmd/ghalint@v1.5.4

      - name: Run ghalint
        run: ghalint run
